
services:
  aspnet-app:
    image: pmi-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: pmi-app
    restart: unless-stopped
    volumes:
      - ./pmi-interface/build/:/app/wwwroot
      - ./pmi/bin/Debug/net9.0:/app
